- name: Instalar Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Instalar Docker Compose
  apt:
    name: docker-compose
    state: present
    update_cache: yes

- name: Crear directorio Docker Registry
  file:
    path: /opt/docker-registry
    state: directory

- name: Crear docker-compose.yml para Docker Registry
  copy:
    dest: /opt/docker-registry/docker-compose.yml
    content: |
      version: '3'
      services:
        registry:
          image: registry:2
          ports:
            - "5000:5000"
          restart: always

- name: Levantar Docker Registry
  command: docker-compose up -d
  args:
    chdir: /opt/docker-registry
